version: '3.7'
services:
  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=app
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=app
  node-app:
    build: ./gate-simulator
    image: node:8.16.2-alpine
    ports:
      - '9999:9999'
